version: '3.1'
services:
  kube:
    build:
      context: kube/
    restart: always
    tty: true
    privileged: true
    cap_add:
      - ALL
    network_mode: host
    volumes:
      - /lib/modules:/lib/modules
      - kubernetes:/etc/kubernetes
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  slate:
    depends_on:
      - kube
    build:
      context: slate/
    restart: always
    command: /bin/sh -c 'set -e; trap "exit 0;" TERM INT; while true; do sleep 1d; done & wait'
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - kubernetes:/etc/kubernetes
volumes:
  kubernetes:
